sudo: required

services:
  - docker

before_install:
  - docker build -t shaileshshail/react-test -f ./client/Dockerfile.dev ./client

#script:
 # - docker run -e CI=true shaileshshail/react-test npm test

after_success:
  - docker build -t shaileshshail/invigilation-client ./client
  - docker build -t shaileshshail/invigilation-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push shaileshshail/invigilation-client
  - docker push shaileshshail/invigilation-server

